name: darehana

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      year:
        description: "[optional] year"
      month:
        description: "[optional] month"
      day:
        description: "[optional] day"
  # 定期実行（月-木 15:30+0900）
  schedule:
    - cron: '30 6 * * 1-4'

env:
  TZ: 'Asia/Tokyo'

jobs:
  execute:
    # イメージ
    runs-on: ubuntu-latest

    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # ダウンロード
      - name: Download file
        run: |
          ENV_Y=${{ github.event.inputs.year }}
          ENV_M=${{ github.event.inputs.month }}
          ENV_D=${{ github.event.inputs.day }}
          Y=${ENV_Y:-`date '+%Y'`}
          M=${ENV_M:-`date '+%m'`}
          D=${ENV_D:-`date '+%d'`}
          echo $Y-$M-$D
          mkdir -p ./darehana/${Y}/${M}/
          cd ./darehana/${Y}/${M}/
          rm -f ${Y}${M}${D}.xml
          if curl "http://radiko.jp/v3/program/date/${Y}${M}${D}/JP13.xml" | grep "山崎怜奈の誰かに話したかったこと。" > /dev/null; then
          curl "https://radiko.jp/v2/api/noa?station_id=FMT&ft=${Y}${M}${D}130000&to=${Y}${M}${D}145500" -o ${Y}${M}${D}.xml
          fi

      # プッシュ
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "Scheduled action"
          git push origin HEAD:main
